name: silangka
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  icons_plus: ^5.0.0
  connectivity_plus: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa/Nexa-ExtraLight.ttf
        - asset: assets/fonts/Nexa/Nexa-Heavy.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
